---
spring:
  profiles: subject
  application:
    name: subject-service
words: I,You,He,She,It

---
spring:
  profiles: verb
  application:
    name: verb-service
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
  application:
    name: article-service
words: a,the

---
spring:
  profiles: adjective
  application:
    name: adjective-service
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
  application:
    name: noun-service
words: boat,book,vote,seat,backpack,partition,groundhog